
-- 2020-09-30
ALTER TABLE `tbl_user`
	ALTER `USER_PASSWORD` DROP DEFAULT;
ALTER TABLE `tbl_user`
	CHANGE COLUMN `USER_PASSWORD` `USER_PASSWORD` VARCHAR(100) NOT NULL COMMENT '회원PW' AFTER `USER_ID`;

ALTER TABLE `tbl_user`
	ADD COLUMN `USER_ROLE` VARCHAR(10) NOT NULL COMMENT '회원권한' AFTER `USER_PASSWORD`;

ALTER TABLE `tbl_user`
	ADD COLUMN `USER_UUID` VARCHAR(32) NOT NULL COMMENT '회원UUID' AFTER `MODE_DATE`;
	